### ISSUE TITLE
Importing csv files with mlcp task

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#103]
I'm having iussues when I try to import csv files with mlcp 8.0-5.
It will not import anything and it also does not give any error messages because the log4j is not configured properly.

The output looks like this:
mlcp arguments, excluding password: [IMPORT, -host, localhost, -port, 8003, -username, admin, -input_file_path, test-data/testfile.csv, -input_file_type, delimited_text, -options_file, mlcp-options/import-options-csv.txt]
log4j:WARN No appenders could be found for logger (com.marklogic.contentpump.ContentPump).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

BUILD SUCCESSFUL

In the options file I have the following properties:
 
-output_uri_replace
".*test-data/,'/'"

-output_collections
data/CSV, data

-output_permissions
app-read-role,read,app-update-role,update,app-insert-role,insert

-transform_namespace
http://namespace/whatever/mlcp-transform

-transform_module
/lib/mlcp-transform.xqy

-transform_function
transform

-delimited_root_name
ROOT_ELM

-namespace
http://namespace/whatever

-delimiter
,

-generate_uri

What do I need to do to configure the log4j system properly?

**Comment by rjrudin** [comment]
See https://github.com/rjrudin/ml-gradle/blob/master/examples/mlcp-project/build.gradle#L52 and https://github.com/rjrudin/ml-gradle/tree/master/examples/mlcp-project/lib for an example of how to enable logging in mlcp.
