### ISSUE TITLE
field range index creation issue

### ISSUE THREAD

**Issue by tzejohn** [rjrudin/ml-gradle#104]
This is just to make you aware of a potential issue in field range index created from mlgradle/management API.  The MarkLogic support ticket # is `17251`. And a stackoverflow discussion around it is [here](http://stackoverflow.com/questions/37859918/field-range-index-is-empty).

Essentially, I am defining a field range index as in:

```
"field": [
    {
      "field-name": "status",
      "field-path": [
        {
          "path": "/pdbe:person-envelope/pdbm:person/pdbm:status",
          "weight": 1
        },
        {
          "path": "/pdbm:person/pdbm:status",
          "weight": 1
        }
      ],
      "field-value-searches": true
    }
]
```

And the index:

```
"range-field-index": [
    {
      "scalar-type": "string",
      "collation": "http://marklogic.com/collation/en/S1",
      "field-name": "status",
      "range-value-positions": false,
      "invalid-values": "reject"
    }
]
```

When I query  with:

```
cts:field-values("status", (), "collation=http://marklogic.com/collation/en/S1")
```

I get an empty sequence back, though a `field-value-query()` works fine.  If I manually go through the admin UI and change the collation to anything else, then after index update, the values come back.  If I then go and try to reindex the whole db from the admin UI, the field range index again has no values.

Support was able to replicate this. Though not with fields that were initially created from the admin UI.  Maybe some json configuration is missing?

**Comment by rjrudin** [comment]
Were you able to reproduce this by just making HTTP PUT requests to the Management API?

**Comment by tzejohn** [comment]
Support was able to, and this was filed as Bug 40405.

-tj


-------- Original message --------

**Comment by rjrudin** [comment]
@tzejohn Thanks for posting this - I'm going to close it so there's no action to take wrt ml-gradle.
