### ISSUE TITLE
Deployment strategy for roles that depend on other roles

### ISSUE THREAD

**Issue by tzejohn** [rjrudin/ml-gradle#108]
We have a case where a role is getting deployed, but a role that it includes had but been defined yet. Is a possible strategy to name files in a certain way to get them to load in a specific order, or is there a way to continue loading, ignoring errors, then deploying again on top to clean up all the errors?

**Comment by xquery** [comment]
see https://github.com/rjrudin/ml-gradle/issues/87 for workaround

**Comment by sastafford** [comment]
Prefix your roles with numbers to indicate the order.

 
 
  On Fri, Jul 1, 2016 at 5:40 AM, TJ Tang<notifications@github.com> wrote:   
We have a case where a role is getting deployed, but a role that it includes had but been defined yet. Is a possible strategy to name files in a certain way to get them to load in a specific order, or is there a way to continue loading, ignoring errors, then deploying again on top to clean up all the errors?

**Comment by rjrudin** [comment]
Also see https://github.com/rjrudin/ml-gradle/tree/master/examples/role-project
