### ISSUE TITLE
chaining tasks

### ISSUE THREAD

**Issue by Luiz-N** [rjrudin/ml-gradle#109]
@rjrudin I currently have a "parent task" that is basically an empty task with two `dependsOn` tasks to chain them together. The first is an mlcp task that loads some data and the second is a corb task.

```
task ingestAndClear (dependsOn: ['mlcpTask', 'corbTask']) {
  println "done ingesting"
}
```

Two questions/issues:

1. These currently get executed in alphabetical order. Is there a way to enforce order that doesn't require messing with the task names? (I know I could have the second task simply depend on the first but I'd like to have the option of isolating the two or adding a third task later on if needed)
2. If the first task fails the seconds still runs. Is there a way to make the execution stop if the preceding task does not complete successfully?

Thanks!

**Comment by rjrudin** [comment]
@Luiz-N - see https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:ordering_tasks - I think mustRunAfter is the right choice here, e.g.

    corbTask.mustRunAfter mlcpTask

For the 2nd question - what kind of failure? If mlcp e.g. can't find the input_file_path, it will throw an exception and return with a non-zero exit value. MlcpTask extends Gradle's JavaExec task - https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html - and by default, that will fail the build if it gets a non-zero exit value.

**Comment by Luiz-N** [comment]
ok good to know on the mustRanAfter and shouldRunAfter options...

My second question came about because given that example parent task trick above the mlcp task has failed with a 
 `2016-07-11 08:37:24 ERROR LocalJobRunner:149 - java.io.IOException: com.marklogic.xcc.exceptions.XQueryException: XDMP-NOSUCHDB: No such database `
error but the following corb task will still run.

I'm starting to think my parent task trick doesn't actually make them dependent on each other so it attempts all of them even if one fails. (the parent task itself won't end up running)

**Comment by rjrudin** [comment]
@Luiz-N It sounds like mlcp may be able to fail without returning a non-zero value when the JVM exists. If that's the case, then Gradle won't know that mlcp failed. The brief test I did with bad connection details verified that mlcp returns a non-zero value in that case, and then the next Gradle task was not executed.
