### ISSUE TITLE
error when deploying to loadbalancer

### ISSUE THREAD

**Issue by tzejohn** [rjrudin/ml-gradle#112]
Not sure if this is specific to mlGradle.  But we have a cluster in AWS fronted by a load balancer.  Pushing to the load balancer results in:

```
Execution failed for task ':mlLoadModules'.
> Unable to insert content at URI: /config/context.xml; cause: Query evaluation request rejected (400, BAD_REQUEST). Is this an XDBC server?
```

Pushing to an individual node by ip works fine.

Any ideas?

**Comment by rjrudin** [comment]
@tzejohn It looks like you're loading a "root" module, correct? In which case it can't be loaded via the REST API, it has to go through XDBC? (If it were under /ext, it could be loaded via the REST API).

Try a test of something else that hits the load balancer - like write a simple Java program using XCC to see if you can do e.g. "fn:current-dateTime()" and get back a response.

**Comment by tzejohn** [comment]
Thanks Rob. Just wondering why it works when not going through the load balancer?



-tj


-------- Original message --------

**Comment by tzejohn** [comment]
@rjrudin when executing `mlReloadModules` against each single node directly works. Does mlgradle load using XCC as well?  None of the inidividual nodes have an XDBC server setup, as far as I can tell.

**Comment by tzejohn** [comment]
@rjrudin I have found the issue.  The HTTP endpoints are also xdbc enabled, but my load balancer was only configured to forward requests as HTTP, so when the protocol switched, it failed.  Switching the load balancer to use TCP as the protocol resolved my issue.

**Comment by rjrudin** [comment]
@tzejohn Cool, good to hear. Just for reference for anyone else reading this - in ML8, port 8000 accepts both HTTP and XDBC requests, which is what ml-gradle will use by default for loading modules. And port 8000 is a REST API server, so it lets you specify which database to load modules into. Any other REST API server can behave in the same way if it uses the OOTB rewriter that enables processing XDBC requests.
