### ISSUE TITLE
cannot overwrite custom local.gradle properties

### ISSUE THREAD

**Issue by Luiz-N** [rjrudin/ml-gradle#118]
@rjrudin , In my build.gradle buildScript I have:

```
  if (new File("local.gradle").exists()) {
      apply from: "local.gradle"
  }
  if (project.hasProperty("mlRestPort")) {
      mlRestPort = project.property("mlRestPort")
    }
  if (project.hasProperty("customProp")) {
      customProp = project.property("customProp")
    }
```
If I have a local.gradle file with a property such as `mlRestPort` but also pass in the same value via `gradle randomTask -PmlRestPort=8200` then the passed in value will override local.gradle. (as expected via my code above) However if I have a custom property set in gradle.properties and local.gradle then attempt to pass in a value the same way local.gradle does not get overwritten. The `customProp` value in local.gradle will still be used later down in tasks when referenced via project.property('customProp').

Potential bug or could I be doing something wrong?

**Comment by rjrudin** [comment]
@Luiz-N I included that technique of using local.gradle before I found out about a Gradle properties plugin - https://github.com/stevesaliman/gradle-properties-plugin . Give that a try, I think that works more reliably.

**Comment by Luiz-N** [comment]
yup, should've checked this out earlier! thanks
