### ISSUE TITLE
mlRedeploy fails when a uri privilege is defined

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#120]
I have created a uri privilege and when I do mlRedeploy I get an error message stating that the action cannot be changed.

Executing command [com.marklogic.appdeployer.command.security.DeployPrivilegesCommand] with sort order [10]
Processing files in directory: D:\projects\tradestore-ml\src\main\ml-config\security\privileges
Processing file: D:\projects\tradestore-ml\src\main\ml-config\security\privileges\1-provenance-uri.json
Sending XML GET request as user with admin role 'admin' to path: /manage/v2/privileges
Found privilege with name of provenance-uri, so updating at path /manage/v2/privileges/provenance-uri/properties?kind=uri
Sending JSON PUT request as user with admin role 'admin' to path: /manage/v2/privileges/provenance-uri/properties?kind=uri
PUT request for "http://localhost:8002/manage/v2/privileges/provenance-uri/properties?kind=uri" resulted in 400 (Bad Request); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"400", "status":"Bad Request", "messageCode":"MANAGE-INVALIDPAYLOAD", "message":"MANAGE-INVALIDPAYLOAD: (err:FOER0000) Payload has errors in structure, content-type or values. Privilege action cannot be changed."}}
:mlDeployApp FAILED

Is this an error in ml-gradle or is this an error in the management API?

I also want to know how I can attach a uri privilege to a role that does not exist yet.
Or does that automatically get attached when I create the role with the uri privilege?

**Comment by rjrudin** [comment]
@xquery Sounds like the Mgmt endpoint for privileges doesn't allow updating the action? Does this sound correct?

@peetkes I'll try reproducing this later today, I know I have an automated test in ml-app-deployer that should try to update a URI privilege.

Also, for associating a role with a URI privilege - I think the better way to do it is to reference the URI privilege in your role file, as a role payload allows for a "privileges" block.

**Comment by peetkes** [comment]
Never mind! You can close this. If ypu don't specuify the endslash on the action it will be added automatically. that's the reason why redeploy fails. It tries to change the action....
