### ISSUE TITLE
Out-of-the-box support for deploying Entity Service models

### ISSUE THREAD

**Issue by jmakeig** [rjrudin/ml-gradle#123]
Probably would want a `ml-models` folder as a sibling of `ml-modules` and `ml-schemas`. Need to be able to configure permissions and collections. Since models go in the content database, they should have `*-admin` visibility by default and should be segregated into a directory, probably mirroring any sub-directories in the local config. They also need to be loaded into the `http://marklogic.com/entity-services/models` collection to be picked up by the default TDE.

This is specific to MarkLogic 9.

**Comment by rjrudin** [comment]
@jmakeig Could you either email me or open up a PR that has sample model files in it? Should be easy to support this.

**Comment by jmakeig** [comment]
Another related aspect is all of the scaffolding that Entity Services provides once you’ve defined a model. From the model Entity Services can generate:

* Transformation code
* Search API options
* Database indexing configuration
* XML schemas
* TDEs for Optic API queries

It would be nice to have some ml-gradle scaffolding that could generate these artifacts as well and put them in the right place. For example, here’s some XQuery to illustrate this:

```xquery
xquery version "1.0-ml";
import module namespace es = "http://marklogic.com/entity-services" at "/MarkLogic/entity-services/entity-services.xqy"; 
import module namespace esi = "http://marklogic.com/entity-services-impl" at "/MarkLogic/entity-services/entity-services-impl.xqy"; 

declare variable $PATH as xs:string := "/Users/jmakeig/Workspaces";

(: this script generates all of the artifacts supported in Entity Services for EA-2 :)
let $project-location := $PATH || "/xdmp-entity-services/entity-services-examples"
let $gen-prefix := $project-location || "/gen/"
let $d := es:entity-type-from-node(fn:doc("simple-race.json"))
return ($d ,
  xdmp:save($gen-prefix || "ml-modules/ext/Race-0.0.1.xqy", es:conversion-module-generate($d)),
  xdmp:save($gen-prefix || "ml-schemas/Race-0.0.1.tdex", es:extraction-template-generate($d)),
  xdmp:save($gen-prefix || "ml-schemas/Race-0.0.1.xsd", es:schema-generate($d)),
  xdmp:save($gen-prefix || "ml-config/databases/content-database.json", es:database-properties-generate($d))
)
```

**Comment by rjrudin** [comment]
Interesting... so you're thinking ml-gradle (really ml-app-deployer, but ml-gradle will expose it) could do something like this:

1. Load any models under ml-models (maybe ml-entity-models? or ml-entities? or ml-es-models? I think we need something more specific than ml-models)
1. For each model, do e.g. a /v1/eval call with something like the code above. I'm thinking it would return a big XML document containing each of those pieces, and then ml-gradle could write them out to the correct place (since xdmp:save won't work if my ML instance is remote)

**Comment by rjrudin** [comment]
@jmakeig Is the design in the above comment suitable?

**Comment by jmakeig** [comment]
Yeah, that sounds good, especially your delineation between loading models and generating artifacts from the model. I like `entity-models` for the directory name. (Why does it need to be prefixed with `ml`?)

To reiterate what you surmised in 2, the generated artifacts need to live on the _local file system_ even though they're generated remotely. The key aspect here is version control. A generated artifact would then be deployed just like any other artifact of its type.

**Comment by rjrudin** [comment]
There's an examples/entity-services-project to show how this works

**Comment by grechaw** [comment]
wow

**Comment by grechaw** [comment]
the future comes so quickly sometimes.
