### ISSUE TITLE
Scaffold more granular roles

### ISSUE THREAD

**Issue by jmakeig** [rjrudin/ml-gradle#124]
Here’s where I’d start:

## Nobody
```json
{
  "role-name": "%%PROJECT_NAME%%-nobody",
  "description": "Unauthenticated user",
  "role": []
}
```

## Reader
```json
{
  "role-name": "%%PROJECT_NAME%%-reader",
  "description": "Can view documents, but not edit",
  "role": ["rest-reader", "%%PROJECT_NAME%%-nobody"]
}
```

## Writer
```json
{
  "role-name": "%%PROJECT_NAME%%-writer",
  "description": "Can read and write documents",
  "role": ["%%PROJECT_NAME%%-reader", "rest-writer"],
  "privilege": [
    { "privilege-name": "any-uri", "action": "http://marklogic.com/xdmp/privileges/any-uri", "kind": "execute"},
    { "privilege-name": "unprotected-collections", "action": "http://marklogic.com/xdmp/privileges/unprotected-collections", "kind": "execute"}
  ]            
}
```

## Admin
```json
{
  "role-name": "%%PROJECT_NAME%%-admin",
  "description": "Non-admin administrator",
  "role": ["manage-admin", "rest-admin", "tde-admin", "%%PROJECT_NAME%%-writer"],
  "privilege": [
    { "privilege-name": "any-uri",        "action": "http://marklogic.com/xdmp/privileges/any-uri",        "kind": "execute"},
    { "privilege-name": "xdbc:insert-in", "action": "http://marklogic.com/xdmp/privileges/xdbc-insert-in", "kind": "execute"},
    { "privilege-name": "xdmp:eval-in",   "action": "http://marklogic.com/xdmp/privileges/xdmp-eval-in",   "kind": "execute"}
  ]
}
```

## Internal
```json
{
  "role-name": "%%PROJECT_NAME%%-internal",
  "description": "Internal role used for amping",
  "role": ["%%PROJECT_NAME%%-writer"]
}
```

And then one user each for admin, writer, and reader. Create a `%%PROJECT_NAME-nobody` user if the app server uses application-level authentication and set that user as the default.

**Comment by jmakeig** [comment]
I’d appreciate feedback on my arrangement of role inheritance and privileges too.

**Comment by rjrudin** [comment]
This looks good, though I haven't really come up with a need for the nobody and internal roles on any application. But it's of course easy to generate them and then let the developer decide what to dump.

Do you think this should be part of the vanilla mlScaffold, or would you want a separate task or a property that must be set? i.e.

gradle mlScaffold -PscaffoldSecurity=true

**Comment by jmakeig** [comment]
Internal is for amping specific write operations to read or even nobody users. 

I'd suggest this setup, or something like it, be the default.

**Comment by rjrudin** [comment]
The code for this is in ml-app-deployer, but I'll track it here too

**Comment by rjrudin** [comment]
Work done here - https://github.com/rjrudin/ml-app-deployer/issues/119

**Comment by jmakeig** [comment]
Another satisfied customer.
