### ISSUE TITLE
mlRestartCluster not working on 8.0.5

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-gradle#127]
Getting this error:

{"errorResponse":{"statusCode":"415", "status":"Unsupported Media Type", "messageCode":"REST-INVALIDMIMETYPE", "message"
:"REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'application/x-www-form-urlencoded', Receiv
ed: application/json"}}* Connection #0 to host localhost left intact

May be an ML bug - filed 41860.

**Comment by xquery** [comment]
FWIW fixed in b8 - should be included in MarkLogic 8.0-6 release

**Comment by rjrudin** [comment]
Thanks @xquery , I'm going to close this since ML is addressing it.
