### ISSUE TITLE
question about paths in json (w/ windows)

### ISSUE THREAD

**Issue by xquery** [rjrudin/ml-gradle#137]
when working with file paths in ml-config properties, I do something like this

```
mlAppConfig {
      customTokens.put("%%ROOT%%",new File("$projectDir/src/test/xquery").getAbsolutePath());
      createTriggersDatabase = false
}
```
where we are performing text substitution in json

```
{
  "server-name": "myTestServer",
  "root": "%%ROOT%%",
  "url-rewriter":"",
  "error-handler":"",
  "modules-database":0
}
```

to try and cater for differences in file paths (escaping in windows for example).

Wondering if this is the right idiom ?

**Comment by rjrudin** [comment]
That looks fine to me. It's been a long time since I didn't use a modules database, so I'm not really familiar with this problem. I also feel like "/" has worked reliably on Windows (and of course Linux too) for me.
