### ISSUE TITLE
Supporting loading data

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-gradle#14]
As part of integrating into samplestack, need a replacement for MarkLogicSlurpTask. This loads documents via the REST API, which is one option - which also includes support for loading triple files. 

Can do REST API initially, though mlcp will of course scale better.

**Comment by rjrudin** [comment]
Don't need for this samplestack anymore, as samplestack has something very custom. But - we can extract parts of what's in MarkLogicSlurpTask to make for an easy way of loading data. It of course needs to be easier than just setting up an MlcpTask too.

**Comment by xquery** [comment]
the scenarios that interest me are;

* one time upload of config data into content db (small)
* upload data into content database
* upload data into multiple content databases (potentially large)
* upload only data that has changed 

bearing in mind that thought needs to be directed to tertiary matters, such as default behaviors eg. 'clear database before load' or append ?

I do not think we need to provide a facade over content pump, though it would be nice to easily do simple data loading tasks.

**Comment by rjrudin** [comment]
Closing this, as I haven't really run into a need for it, and I think things like DMSDK and marklogic-spring-batch are addressing this.
