### ISSUE TITLE
Incorrect Default Property Value in failover-project Example

### ISSUE THREAD

**Issue by ericputnam** [rjrudin/ml-gradle#147]
The mlDatabaseNamesAndReplicaCounts property in

https://github.com/rjrudin/ml-gradle/blob/master/examples/failover-project/gradle.properties

should be changed from
mlDatabaseNamesAndReplicaCounts = ["Security": 2, "Schemas": 1, "Meters": 1, "App-Services": 1]
to
mlDatabaseNamesAndReplicaCounts=Security,2,Schemas,1,Meters,1,App-Services,1

**Comment by rjrudin** [comment]
@ericputnam Thanks for the catch! Making the update now.
