### ISSUE TITLE
my gradle is built and running successfully but not updating the values from the configs.

### ISSUE THREAD

**Issue by devarajanv** [rjrudin/ml-gradle#150]
I’m using ML gradle for the first time and also I'm fairly new to Gradle build process.

My folder structure is: /src/ml/ml-config/ and /src/ml/ml-modules[default was /src/main/ml-config/ and /src/main/ml-modules]. This is where i have the config files.

Databases(content, module and trigger) and HTTP App server are created with mlAppName and mlRestPort as available in the properties file. 
But I’m trying to update some database values like triple index value and collection lexicon value, and trying to create XDBC appserver. [Attached files, FYI]

I’m not getting any error when I run “gradle –i mlDeploy --stacktrace”. If something is incorrect with my set up, then i'd like to throw them as error in the console so that i can correct it.

Some logs below for your reference(Excuse me for the newline breaks here… ): Looks like the commands are executed but not from the newly json file. Please let me know what am I missing here. 

.
.
.
Executing command [com.marklogic.appdeployer.command.appservers.UpdateRestApiSer
versCommand] with sort order [250]
No REST API server file found at C:\workspace\marklogic_abv-pubmed\src\main\ml-c
onfig\servers\rest-api-server.json, so not updating the server
Finished executing command [com.marklogic.appdeployer.command.appservers.UpdateR
estApiServersCommand]

Executing command [com.marklogic.appdeployer.command.appservers.DeployOtherServe
rsCommand] with sort order [300]
Finished executing command [com.marklogic.appdeployer.command.appservers.DeployO
therServersCommand]
.
.
.
.

Deployed app pubmed
:mlDeployApp (Thread[Daemon worker Thread 13,5,main]) completed. Took 14.131 sec
s.
:mlPostDeploy (Thread[Daemon worker Thread 13,5,main]) started.
:mlPostDeploy
Skipping task ':mlPostDeploy' as it has no actions.
:mlPostDeploy UP-TO-DATE
:mlPostDeploy (Thread[Daemon worker Thread 13,5,main]) completed. Took 0.001 sec
s.
:mlDeploy (Thread[Daemon worker Thread 13,5,main]) started.
:mlDeploy
Skipping task ':mlDeploy' as it has no actions.
:mlDeploy (Thread[Daemon worker Thread 13,5,main]) completed. Took 0.001 secs.

BUILD SUCCESSFUL

Total time: 17.16 secs

**build.gradle**

buildscript {
    repositories {
        jcenter()
        mavenLocal()
    }
    dependencies {
        classpath "com.marklogic:ml-gradle:${mlGradleVersion}"
    }
}

apply plugin: "com.marklogic.ml-gradle"

ext {
    mlAppConfig {
        modulePaths = ["src/ml/ml-modules/"]
        customTokens.put("%%XDBC_PORT%%", "8104")
    }

}

**gradle.properties**
mlGradleVersion=2.4.0

mlHost=localhost
mlUsername=admin
mlPassword=admin
mlAppName=test
mlRestPort=8010

**content-database.json**
{
  "database-name" : "%%DATABASE%%",
  "triggers-database": "%%TRIGGERS_DATABASE%%",
  "triple-index": true,
  "collection-lexicon": true
}

**xdbc-server.xml**
<xdbc-server-properties xmlns="http://marklogic.com/manage">
  <server-name>%%NAME%%-xdbc</server-name>
  <group-name>%%GROUP%%</group-name>
  <server-type>xdbc</server-type>
  <root>/</root>
  <port>%%XDBC_PORT%%</port>
  <content-database>%%DATABASE%%</content-database>
  <modules-database>%%MODULES_DATABASE%%</modules-database>
</xdbc-server-properties>

**Comment by sastafford** [comment]
Have you checked out the examples directory?  There are a lot of use cases.  Check out the sample-project. 

https://github.com/rjrudin/ml-gradle/tree/master/examples/sample-project

**Comment by devarajanv** [comment]
Yes @sastafford. I took sample-project and i was working on top of it. Issue was with my folder structure. as i changed it from "main" to "ml" it stopped working as gradle's path was looking for /src/main/ml-config/ and /src/main/ml-modules/. I've corrected it, it is working fine now.

**Comment by rjrudin** [comment]
@devarajanv Can I close this since the fix was to change "ml" to "main"? I have a separate ticket open for documenting all the possible folders under ml-config.

**Comment by devarajanv** [comment]
Yes, please close this issue.
