### ISSUE TITLE
Ability to undeploy custom forest configuration

### ISSUE THREAD

**Issue by Luiz-N** [rjrudin/ml-gradle#156]
[Deploying custom forests](https://github.com/rjrudin/ml-gradle/tree/master/examples/custom-forests-and-replicas-project/src/main/ml-config/forests/custom-forests-example-contentl) works great but they don't seem to be undeployed when running `gradle mlUndeploy`.

Is this simply not implemented yet or is there something I might be missing?

**Comment by rjrudin** [comment]
There's actually not any support for it yet; the thought being that "undeploying" forests = deleting them, in which case it should be much faster to just delete the database that they're attached to and then recreate the database (that takes 2 calls, whereas undeploying forests requires N calls where N = number of forests). 

Can I get more details on your use case? Are you looking to delete all the forests and then start with a default set of N per host? Or delete them all and start with a new custom set?

**Comment by Luiz-N** [comment]
The challenge is that deleting the database doesn't delete the forests. Then when a fresh deploy is attempted the task fails since the custom forests already exist in ML.

Our current use case involves very specific custom forest configurations where undeploying and deploying is not uncommon during the development cycle.

**Comment by rjrudin** [comment]
How are you deleting the database? The DeployDatabaseCommand has a forestDelete property that is set to "data", which means the forests will be deleted - see http://docs.marklogic.com/REST/DELETE/manage/v2/databases/[id-or-name] .

**Comment by rjrudin** [comment]
@Luiz-N I'm not sure what to do here yet - still wondering how you're deleting your database, as that should default to deleting all the forests too.

**Comment by rjrudin** [comment]
This should be resolved now in 2.6.0 - there definitely was a bug where replicas were not deleted if ml-gradle didn't explicitly know about them.
