### ISSUE TITLE
Allow file system tree structure for specifying the group a scheduled task will be created in

### ISSUE THREAD

**Issue by tcfenstermaker** [rjrudin/ml-gradle#157]
Scheduled Tasks in MarkLogic are created by group. By default, these are going into the _Default_ group. There is currently no built-in mechanism thru `ml-gradle` for specifying an alternate group. This is because the Management REST API for creating scheduled tasks does not accept the group-id in the payload, but rather as a URL parameter:

[https://docs.marklogic.com/REST/POST/manage/v2/tasks](https://docs.marklogic.com/REST/POST/manage/v2/tasks)

`ml-gradle` has no mechanism for handling configurable URL parameters. By design, it expects the payload file to conform to the `$ML_HOME/config/manage-task-properties.xsd` schema, which precludes adding any non-payload metadata (such as URL parameters). We can preserve the current `ml-gradle` conventions by creating a tree structure under `/tasks`, where the parent directory will be the group. For example:

`src/main/ml-config/tasks/HA/task-1.json`

would create `task-1` under the _HA_ group instead of the _Default_ group.

**Comment by rjrudin** [comment]
https://github.com/rjrudin/ml-app-deployer/issues/137 resolves this

**Comment by rjrudin** [comment]
Summary of resolution - any child directory under ml-config/tasks has its name used as the group name to add the task to.
