### ISSUE TITLE
property for setting ml-config and ml-modules dir

### ISSUE THREAD

**Issue by xquery** [rjrudin/ml-gradle#17]
might exist already ?

**Comment by rjrudin** [comment]
The sample-project shows an example of changing the config dir - https://github.com/rjrudin/ml-gradle/blob/master/sample-project/gradle.properties#L41 . 

For the modules dir - multiple dirs are supported. I'll add an example to sample-project for it.

**Comment by rjrudin** [comment]
See the PR - https://github.com/rjrudin/ml-gradle/pull/21

**Comment by xquery** [comment]
thx for the pointer
