### ISSUE TITLE
Password Support

### ISSUE THREAD

**Issue by RobertSzkutak** [rjrudin/ml-gradle#171]
Is it possible to use passwords not stored in plain text in the properties file?

For example, Roxy supports supplying passwords via the command line or an environment variable. I've also seen customers supply an "encrypted password" via the command line to Roxy and then extend Roxy to decrypt their password.

**Comment by sastafford** [comment]
Gradle supports passing in properties such as passwords using the -P option.

https://docs.gradle.org/current/userguide/gradle_command_line.html

Can also use environment variables. 

Gradle is really just groovy/java underneath the hood so it can decrypt password tokens as well.  Most customers I've come across seem fine passing in the password as a parameter.  

Recommend to close, unless there is a hard requirement to decrypt passwords on the fly.

**Comment by RobertSzkutak** [comment]
Thanks will close this. I recommend documenting this somewhere on the ml-gradle wiki.
