### ISSUE TITLE
Support Multiple Users

### ISSUE THREAD

**Issue by RobertSzkutak** [rjrudin/ml-gradle#172]
Roxy has the ability to support multiple user accounts.

There is an "admin" user which can perform bootstrapping (MarkLogic resource configuration). There is a "deploy user" which can support module/content deployment. There is an "MLCP User" for MLCP. A "CORB User", etc. There is also a "default user" used when the other users do not exist.

This functionality is useful because it allows admins, developers and data loaders to share a project configuration without allowing them too much room to run eachothers tasks.

This is also useful for situations where the REST API server has LDAP enabled but XCC does not and vice versa.

**Comment by sastafford** [comment]
In the design of the Management API, engineering created several roles manage-* that can be assigned to users that have the access to create the various MarkLogic resources.  

The users with these predefined roles can be indicated in a [gradle.properties](https://github.com/rjrudin/ml-gradle/blob/master/examples/sample-project/gradle.properties) file.   

The [users and roles](https://github.com/rjrudin/ml-gradle/tree/master/examples/sample-project/src/main/ml-config/security) indicated in this gradle.properties file are specified as part of the ml-config.  

Recommend to close issue.

**Comment by RobertSzkutak** [comment]
Thanks, despite running a couple ml-gradle jobs I hadn't yet noticed that. Something else to document ;-) It's not necessary but it would be nice to have the MLCP and CORB user also supported as I know of a couple Roxy shops where those are used.

**Comment by sastafford** [comment]
Any user that has write privileges to a database can use mlcp or corb.  The idea is you define user/role resources either through ml-config or manually that can execute mlcp or corb jobs.  There are MarkLogic OOTB roles (rest-reader, rest-writer) that you can assign to those users.  Or you just create them yourself.

**Comment by RobertSzkutak** [comment]
"Any user that has write privileges to a database can use mlcp or corb."

If you're using MLCP/CORB to update existing data the permissions can be locked down enough that most users cant run the job to completion. There could also be URI privs or protected collections stopping you from adding new data. A major customer I consult with prevents most users from being able to update data with MLCP/CORB as a safety measure.

I admittedly haven't tried the ml-gradle integration of these tools yet but Roxy saves you quite a bit of typing in the command line or config file by filling in options for you based on your properties. Its quite convenient.

**Comment by rjrudin** [comment]
The ml-gradle home page links to a sample project that is recommended as a good place to start exploring all the ml-gradle features, along with a couple dozen other projects. I added a Wiki page that also links to that project now too - https://github.com/rjrudin/ml-gradle/wiki/Configuring-different-users-for-different-jobs

**Comment by rjrudin** [comment]
Closing this, I think the Wiki page addresses the request
