### ISSUE TITLE
Updating Gradle

### ISSUE THREAD

**Issue by RobertSzkutak** [rjrudin/ml-gradle#174]
Document an update process or build an auto-updater for Gradle similar to how Roxy updates itself

**Comment by sastafford** [comment]
The ml-gradle uses Maven for updates.  It is consistent with how [Gradle deals with dependency management](https://docs.gradle.org/current/userguide/artifact_dependencies_tutorial.html).  The ml-gradle version is specified in the build.gradle file.   

    id "com.marklogic.ml-gradle" version "2.6.0"

**Comment by sastafford** [comment]
Recommend close

**Comment by RobertSzkutak** [comment]
Makes sense to me. I'd like to see this documented for the non-Java guys though. I'd be happy to help work on the wiki if you'd like.

**Comment by rjrudin** [comment]
Added a small Wiki page - https://github.com/rjrudin/ml-gradle/wiki/Upgrading-ml-gradle 

I want to be careful of not reproducing Gradle documentation itself - ml-gradle after all is a plugin for Gradle, and Gradle has copious documentation itself already on the subject of Gradle plugins.

**Comment by RobertSzkutak** [comment]
Good enough for me!
