### ISSUE TITLE
Special characters for the admin password are not being recognized

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#23]
Given mlAdminPassword=[some character string with a $ or other special character]
When I run gradlew -PmlAdminPassword=abc$123 mlDeploy
Then I get a 401 Error when trying to create the roles

**Comment by rjrudin** [comment]
Gradle requires that you escape the "$" sign, so do -PmlAdminPassword=abc\$123 mlDeploy. 

I think it's only for "$", as Gradle interprets that as the start of a variable reference.

**Comment by aajacobs** [comment]
Does this only apply if the password is given on the command line with the -P option?  So if a password with a '$'character in it is listed in gradle.properties, all works fine?

**Comment by oarcm** [comment]
I have the same question as aajacobs.  Is this only for -P option?

**Comment by rjrudin** [comment]
I believe the "$" character is fine in a Java properties file, which gradle.properties is an instance of.
