### ISSUE TITLE
build failed : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by hugokoopmans** [rjrudin/ml-gradle#25]
Hi Rob,

not sure if this is the right place to log this but I have the obi-ui ez app and want to install in on a vm.

I used Geert Josten his vagrant file to create a ml8 vm...

now Itry to do ./gradlew mlinstall and bump into this :

[vagrant@obi-ml8-ml1 obi-ui]$ ./gradlew mlinstall
Downloading https://services.gradle.org/distributions/gradle-2.1-bin.zip
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /home/vagrant/.gradle/wrapper/dists/gradle-2.1-bin/2pk0g2l49n2sbne636fhtlet6a/gradle-2.1-bin.zip to /home/vagrant/.gradle/wrapper/dists/gradle-2.1-bin/2pk0g2l49n2sbne636fhtlet6a
Set executable permissions for: /home/vagrant/.gradle/wrapper/dists/gradle-2.1-bin/2pk0g2l49n2sbne636fhtlet6a/gradle-2.1/bin/gradle
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-gradle/2.0-alpha-4/ml-gradle-2.0-alpha-4.pom
Download https://repo1.maven.org/maven2/org/codehaus/groovy/modules/http-builder/http-builder/0.7/http-builder-0.7.pom
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-app-deployer/2.0-alpha-3/ml-app-deployer-2.0-alpha-3.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.2.1/httpclient-4.2.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.2.1/httpcomponents-client-4.2.1.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/6/project-6.pom
Download https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.3/json-lib-2.3.pom
Download https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.pom
Download https://repo1.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.pom
Download https://repo1.maven.org/maven2/org/apache/apache/3/apache-3.pom
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-javaclient-util/2.0.3/ml-javaclient-util-2.0.3.pom
Download https://repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.pom
Download https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-web/4.1.5.RELEASE/spring-web-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/11/commons-parent-11.pom
Download https://repo1.maven.org/maven2/org/apache/apache/4/apache-4.pom
Download https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/9/commons-parent-9.pom
Download https://repo1.maven.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/5/commons-parent-5.pom
Download https://repo1.maven.org/maven2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.pom
Download https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.1.3/logback-parent-1.1.3.pom
Download https://repo1.maven.org/maven2/com/marklogic/java-client-api/3.0.1/java-client-api-3.0.1.pom
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-xcc-util/2.0.1/ml-xcc-util-2.0.1.pom
Download https://repo1.maven.org/maven2/org/jdom/jdom2/2.0.5/jdom2-2.0.5.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-context/4.1.5.RELEASE/spring-context-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.12/slf4j-parent-1.7.12.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-aop/4.1.5.RELEASE/spring-aop-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-beans/4.1.5.RELEASE/spring-beans-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-core/4.1.5.RELEASE/spring-core-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.pom
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.7/slf4j-parent-1.7.7.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.17/jersey-client-1.17.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-project/1.17/jersey-project-1.17.pom
Download https://repo1.maven.org/maven2/net/java/jvnet-parent/1/jvnet-parent-1.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-apache-client4/1.17/jersey-apache-client4-1.17.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-contribs/1.17/jersey-contribs-1.17.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-multipart/1.17/jersey-multipart-1.17.pom
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.7/commons-codec-1.7.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/26/commons-parent-26.pom
Download https://repo1.maven.org/maven2/org/apache/apache/9/apache-9.pom
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.17/jersey-core-1.17.pom
Download https://repo1.maven.org/maven2/org/jvnet/mimepull/mimepull/1.9.4/mimepull-1.9.4.pom
Download https://repo1.maven.org/maven2/net/java/jvnet-parent/4/jvnet-parent-4.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.4/jackson-parent-2.4.pom
Download https://repo1.maven.org/maven2/com/fasterxml/oss-parent/16/oss-parent-16.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.4.1/jackson-annotations-2.4.1.pom
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.pom
Download http://developer.marklogic.com/maven2/com/marklogic/marklogic-xcc/8.0.2/marklogic-xcc-8.0.2.pom
Download https://repo1.maven.org/maven2/org/springframework/spring-expression/4.1.5.RELEASE/spring-expression-4.1.5.RELEASE.pom
Download https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.pom
Download https://repo1.maven.org/maven2/org/jvnet/mimepull/1.6/mimepull-1.6.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.3.5/httpcomponents-client-4.3.5.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/project/7/project-7.pom
Download https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.pom
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.3.2/httpcomponents-core-4.3.2.pom
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.pom
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom
Download https://repo1.maven.org/maven2/org/apache/commons/commons-parent/34/commons-parent-34.pom
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-gradle/2.0-alpha-4/ml-gradle-2.0-alpha-4.jar
Download https://repo1.maven.org/maven2/org/codehaus/groovy/modules/http-builder/http-builder/0.7/http-builder-0.7.jar
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-app-deployer/2.0-alpha-3/ml-app-deployer-2.0-alpha-3.jar
Download https://repo1.maven.org/maven2/net/sf/json-lib/json-lib/2.3/json-lib-2.3-jdk15.jar
Download https://repo1.maven.org/maven2/net/sourceforge/nekohtml/nekohtml/1.9.16/nekohtml-1.9.16.jar
Download https://repo1.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-javaclient-util/2.0.3/ml-javaclient-util-2.0.3.jar
Download https://repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-web/4.1.5.RELEASE/spring-web-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/commons-beanutils/commons-beanutils/1.8.0/commons-beanutils-1.8.0.jar
Download https://repo1.maven.org/maven2/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar
Download https://repo1.maven.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Download https://repo1.maven.org/maven2/net/sf/ezmorph/ezmorph/1.0.6/ezmorph-1.0.6.jar
Download https://repo1.maven.org/maven2/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.1.3/logback-classic-1.1.3.jar
Download https://repo1.maven.org/maven2/com/marklogic/java-client-api/3.0.1/java-client-api-3.0.1.jar
Download http://rjrudin.github.io/marklogic-java/releases/com/marklogic/ml-xcc-util/2.0.1/ml-xcc-util-2.0.1.jar
Download https://repo1.maven.org/maven2/org/jdom/jdom2/2.0.5/jdom2-2.0.5.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-context/4.1.5.RELEASE/spring-context-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.12/jcl-over-slf4j-1.7.12.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-aop/4.1.5.RELEASE/spring-aop-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-beans/4.1.5.RELEASE/spring-beans-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-core/4.1.5.RELEASE/spring-core-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
Download https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.1.3/logback-core-1.1.3.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-client/1.17/jersey-client-1.17.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-apache-client4/1.17/jersey-apache-client4-1.17.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/contribs/jersey-multipart/1.17/jersey-multipart-1.17.jar
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.7/commons-codec-1.7.jar
Download https://repo1.maven.org/maven2/com/sun/jersey/jersey-core/1.17/jersey-core-1.17.jar
Download https://repo1.maven.org/maven2/org/jvnet/mimepull/mimepull/1.9.4/mimepull-1.9.4.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.4.1/jackson-core-2.4.1.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.4.1/jackson-annotations-2.4.1.jar
Download https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.4.1/jackson-databind-2.4.1.jar
Download http://developer.marklogic.com/maven2/com/marklogic/marklogic-xcc/8.0.2/marklogic-xcc-8.0.2.jar
Download https://repo1.maven.org/maven2/org/springframework/spring-expression/4.1.5.RELEASE/spring-expression-4.1.5.RELEASE.jar
Download https://repo1.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
Download https://repo1.maven.org/maven2/org/jvnet/mimepull/1.6/mimepull-1.6.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.5/httpclient-4.3.5.jar
Download https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
Download https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.12/slf4j-api-1.7.12.jar
Download https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'obi-ui'.
> Could not open no_buildscript class cache for build file '/space/projects/obi/obi-ui/build.gradle' (/home/vagrant/.gradle/caches/2.1/scripts/build_2tv2dt3jfe4uuce4od0jn6fp28/ProjectScript/no_buildscript).
   > com/marklogic/gradle/task/MlcpTask : Unsupported major.minor version 51.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 37.079 secs
[vagrant@obi-ml8-ml1 obi-ui]$ 

please advise

**Comment by rjrudin** [comment]
Gotta have at least Java 1.7 - it'll run on Java 1.8 too. 

http://stackoverflow.com/questions/20690143/java-unsupported-major-minor-version-51-0
