### ISSUE TITLE
gradle mlWatch not working

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#3]
Error: Could not find or load main class com.marklogic.client.modulesloader.ModulesWatcher

WatchTask.groovy line 16

wrong classpath referenced

**Comment by rjrudin** [comment]
Crap. Just fixed it, and I cheated and republished version 1.0 of ml-gradle, which means you'll need to remove that from your local Gradle cache. 

This can also be temporarily fixed in a Gradle file - just override the property:

mlWatch.main = "the correct class name"
