### ISSUE TITLE
Execute mlPostDeploy task as mlManageUsername

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#30]
As a developer

I want to TITLE

So that I can avoid using the default permissions assigned to mlRestAdminUsername

I am using the mlPostDeploy task to create a few triggers but the create triggers task uses the default permissions of the user (mlRestAdminUserName).  As a result, I've had to assign the createTriggers execute priv to that user.  I don't think we want that user creating triggers.  One way to address this problem would be to change the createTriggersTask to not use xdmp:default-permissions().  But it may be a better solution to have mlManageUsername run the postDeploy task.

**Comment by rjrudin** [comment]
You can do this already, and note that "mlPostDeploy" is a task that doesn't actually do anything - it's just a hook for you to add other tasks to via dependsOn.

You're presumably creating the task via CreateTriggersTask, and that task has an xccUrl as a parameter. Just provide an XCC URL that uses the user that you want to create the trigger with - e.g. xcc://host:port@some-admin-or-manager:password .
