### ISSUE TITLE
Waiting for restart trips over NoHttpResponseException

### ISSUE THREAD

**Issue by grtjn** [rjrudin/ml-gradle#31]
I was undeploying, and the check to see if a restart finished threw an error:

```
:mlAppUndeploy
Caught exception while waiting for MarkLogic to restart: I/O error on GET request for "http://ml8-ml1:8001/admin/v1/timestamp":ml8-ml1:8001 failed to respond; nested exception is org.apache.http.NoHttpResponseException: ml8-ml1:8001 failed to respond
:mlAppUndeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlAppUndeploy'.
> I/O error on GET request for "http://ml8-ml1:8002/manage/v2/databases":ml8-ml1:8002 failed to respond; nested exception is org.apache.http.NoHttpResponseException: ml8-ml1:8002 failed to respond
```

**Comment by rjrudin** [comment]
Can you provide the following:

- Your build.gradle file
- Your gradle.properties
- The gradle command that you executed
- The version of ML that you're on

**Comment by grtjn** [comment]
I was running `gradle mlundeploy` inside the obi folder of the obp project (after having done a `gradle mldeploy` successfully first). I am running against 8.0-3 in a centos vm..

**Comment by rjrudin** [comment]
What branch of OBI is this?

**Comment by grtjn** [comment]
master of course! ;-)

**Comment by grtjn** [comment]
Note: running mlundeploy a second time ran smooth. It really was just the restart check that failed earlier..

**Comment by rjrudin** [comment]
I bumped OBI up to 2.0a15, undeploy works fine on that.
