### ISSUE TITLE
Add task for deploying groups

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-gradle#33]
Need to add DeployGroupsCommand to mlDeploy too

**Comment by grtjn** [comment]
Supporting groups, tricky. You need to take moving hosts over to other groups as well, which isn't always trivial..

**Comment by rjrudin** [comment]
For now, I'm just promoting "Supports the Default group", as that's all I've tested, and using other groups seems to not happen that much.

**Comment by grtjn** [comment]
Depends who you talk to. There is a fair number of customers with complex cluster configurations.. ;-)

**Comment by rjrudin** [comment]
Yeah - though ml-gradle always provides the escape hatch of a ManageClient that simplifies making requests to the management API. So as long as the management API supports the customer need, the customer can always script together the commands via HTTP requests.

**Comment by rjrudin** [comment]
Now have "mlDeployGroups", and DeployGroupsCommand is in mlDeploy as well, and it's smart enough to wait for a restart (via changes to ml-app-deployer).
