### ISSUE TITLE
MLCP Export Task doesn't seem to work due to invaild host

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#37]
I am running a virtual host on my laptop and it is possible that might be the reason.  But I can pass my host via command line and it is still not being picked up.  

task exportGeonamesTaxonomy(type: com.rjrudin.marklogic.gradle.task.MlcpTask) {
    classpath = configurations.mlcp
    command = "EXPORT"
    database = testFlag.equals("true") ? mlAppConfig.testContentDatabaseName : mlAppConfig.contentDatabaseName
    port = testFlag.equals("true") ? mlAppConfig.testRestPort : mlAppConfig.restPort 
    args = ['-collection_filter', 'org.geonames', '-output_file_path', '$projectDir/src/main/resources/geonames/archive', '-output_type', 'archive']
}

15/09/06 06:23:03 ERROR contentpump.LocalJobRunner: Error running task:
java.lang.IllegalArgumentException: Default provider - Not a usable net address:localhost.localdomain:8100
        at com.marklogic.xcc.ContentSourceFactory.defaultConnectionProvider(Cont
entSourceFactory.java:331)
        at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSource
Factory.java:219)
        at com.marklogic.xcc.ContentSourceFactory.newContentSource(ContentSource
Factory.java:243)

**Comment by rjrudin** [comment]
Try setting the "host" task attribute to whatever the correct value should be. MlcpTask isn't doing anything that would have any effect here.

**Comment by rjrudin** [comment]
Scott, I'm going to close this as I don't think there's anything to be done in ml-gradle.
