### ISSUE TITLE
Application-level auth not supported

### ISSUE THREAD

**Issue by aajacobs** [rjrudin/ml-gradle#41]
Some of the gradle tasks (e.g., mlLoadModules) aren't supported with application-level authentication on the appserver.  The workaround currently is to give the default user the rest-admin role, but it would be nice to have ml-gradle handle this type of server configuration automatically.

**Comment by rjrudin** [comment]
If you can authenticate using the Java API - i.e. the DatabaseClient - then you should be able to do it with ml-gradle. 

The Java API authentication class - https://docs.marklogic.com/javadoc/client/com/marklogic/client/DatabaseClientFactory.Authentication.html - doesn't have an enumerated value for application level security, but I believe that means that you can get away with not submitting a username or password. Try modifying mlAppConfig in your Gradle file:

mlAppConfig {
  restAuthentication = null
  restAdminUsername = null (or "")
  restAdminPassword = null
}

That may do the trick. If you can verify that you can authenticate using a DatabaseClient and you can't do it with ml-gradle, let me know, I'll look further into it.

**Comment by aajacobs** [comment]
I haven’t had a chance to test your theory, but I believe it will work.  However, the broader issue is that if we’re successful in not sending any credentials for the deploy, the default user is the one whose permissions will be used for deploy tasks.  In order for this to work, the default user has to have the rest-admin or maybe even admin role. So, I see at least few options for this:

(1) Just add the rest-admin role to the json config file so it’ll be automatically created, and then remember to take it away when you’re done with the deploy (not ideal since you have to manually do this each time or risk leaving the default user with too many privs by default).
(2) Create a new REST server that points to the same DB that uses digest auth, and use that for deploy tasks.  The server could be dynamically created at the beginning of a task and torn down at the end of it, but then we’d incur a ML restart.
(3) Enhance ml-gradle so if app-level authorization is used, an “amp” role for deploy tasks can also be specified in the configuration, and ml-gradle would amp the default user’s permissions accordingly before executing.

Andrew Jacobs
Sales Engineer
MarkLogic Corporation
andrew.jacobs@marklogic.com
Phone: +1 703 462 0502
www.marklogic.com<http://www.marklogic.com/>
[cid:58707E8B-C680-40E4-A1CE-EBF107BE6D93]

**Comment by rjrudin** [comment]
Hey Andrew - I think this is outside the realm of ml-gradle; the REST API endpoints for loading options/transforms/extensions require the rest-admin role (not the admin role, just rest-admin), and there's not a way around that. 

Still, I think you can authenticate against app-level via the Java Client API by not sending a password (in this case, just sending a username - the user with rest-admin, who's not the default user).

**Comment by sastafford** [comment]
When you instantiate a DatabaseClient, if you pass in the host, port, and database name only it assumes no security per the Java API client javadocs.  

I have a proposed solution to get us over this issue.  I've created an extra XDBC server with digestbasic to handle mlcp, corb, ml-app-deployer, etc.  But I'm not seeing an XDBC port anywhere in the code.  I could override the restPort via the mlAppConfig task, but I might have some syntax issue here.

    ext{
      mlAppConfig {
          restPort = mlXdbcPort
      }
    }

**Comment by rjrudin** [comment]
restPort looks correct, you can verify against the javadocs - http://rjrudin.github.io/marklogic-java/javadocs/ml-app-deployer/com/rjrudin/marklogic/appdeployer/AppConfig.html

mlXdbcPort is something you would need to define in gradle.properties - ml-gradle has no need for an XDBC server, so it doesn't define/expect any XDBC port properties.

**Comment by rjrudin** [comment]
Andrew, I'm going to close this out, as I believe this is supported, but it's an issue with the REST Client API in terms of being able to load modules.
