### ISSUE TITLE
Check for updates and tell the user if a newer ml-gradle exists

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-gradle#52]
Not sure how this gets done, but I've seen ml-gradle have about 3 new builds since I started using it 2 weeks ago. An automagic way to check and tell me would be so awesome.

**Comment by rjrudin** [comment]
You can use "+" to ask for the latest version. Examples:

"com.rjrudin:ml-gradle:2.0b+"

"com.rjrudin:ml-gradle:+"

I just verified this on a project that was using 2.0b10 - I changed it to 2.0b+, and it pulled down 2.0b11.

**Comment by paxtonhare** [comment]
sounds like the best solution. Problem solved.
