### ISSUE TITLE
Need support for MLCP streaming

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-gradle#53]
See here: https://docs.marklogic.com/guide/ingestion/content-pump#id_16000

I need to be able to specify -streaming

I would consider a pull request but I'm not 100% sure how to test it.

**Comment by sastafford** [comment]
The mlcp task does not support the full list of arguments yet.   For those that are missing try adding the following line to your mlcp task.

    args = ['-aggregate_record_element', 'Description', '-aggregate_record_namespace', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#']

**Comment by rjrudin** [comment]
Right - the attributes on MlcpTask are just syntactic sugar, and it guesses your host/port/username/password for you. You can always use JavaExec instead, and like Scott mentions, args lets you specify anything you want.

**Comment by paxtonhare** [comment]
I missed the args bit. That's what I need. Sweet.
