### ISSUE TITLE
Know which user is executing the various REST API calls

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#55]
As a user

I want to TITLE

So that I can know which user is executing each command and troubleshoot any privileges issue.

Example
:mlDeployApp

INFO: admin@http://localhost:8002/v2/manage/....

I'm flexible on how this information shows up in the logs.

**Comment by rjrudin** [comment]
Run Gradle with "--info" or "-" - you'll get a bunch of logging like this:

Initializing ml-gradle
App name:
App host:
App REST port:
App test REST port:
REST Admin username:

**Comment by sastafford** [comment]
I routinely work with the -i flag when running gradle as well.  I think we can improve the log statements that are being transmitted to make it clear which REST Management API calls are being made.  

For example, "Updated server at /manage/v2/servers/wb-portal/properties?group-id=Default"

I would suggest changing this to: [USERNAME] POST /manage/v2/servers/wb-portal/properties 

This indicates the user making the call and the management api endpoint being called.  The HTTP method prefixed is added to show consistency with the REST API documentation.  I think for new users to ml-gradle to make an easier connection to the management API.  Just some lessons learned from World Bank.  

The details of which user is calling the management API is not easy to find.  That needs to be more prevalent.

**Comment by rjrudin** [comment]
Scott - want to take a crack at a PR for this? I think this can all be done in ManageClient. When a ManageConfig instance is passed in, save off the username - and do that for config.getAdminUsername as well. Now when a method is called, you know the manage username / admin username, and you can log it. 

Note that ManageClient is logging at the debug level. If you run Gradle with --debug, you'll get a truckload of logging initially by Gradle itself, but then it calms down a bit. You do get a fair amount of logging from Spring, but I feel for this use case, it's not important to see the username every time you run Gradle or even with "--info" - I think it's reasonable to use the "--debug" command to see what user is being used to make the request.

**Comment by rjrudin** [comment]
Addressed this in 2.0b13 of ml-app-deployer - logging the user, the path, the content type, and the HTTP method on every request at the info level
