### ISSUE TITLE
Latest mlcp 1.3-3 not working

### ISSUE THREAD

**Issue by paxtonhare** [rjrudin/ml-gradle#57]
I'm not sure what changed in the latest mlcp 1.3-3, but it's making running it from gradle difficult. This could very much be an issue with my gradle-fu.

Here are the bits from my build.gradle:
```groovy
configurations {
  mlcp
}

dependencies {
  // mlcp dependencies for import and export
  mlcp "com.marklogic:mlcp:1.3-3"
  mlcp "com.marklogic:marklogic-mapreduce2:2.1.3"
}

task importData(type: com.rjrudin.marklogic.gradle.task.MlcpTask) {
  classpath = configurations.mlcp
  command = "IMPORT"
  port = 8000
  database = mlAppConfig.contentDatabaseName
  input_file_path = dataImportDir
  output_uri_prefix = "/pdf"
  output_collections = "pdf"
  output_permissions = "rest-reader,read,rest-writer,update"
  output_uri_replace = ".*data,''"
  document_type = "binary"
}
```

Right out of the gate it starts complaining about missing log4j config. So I created a log4j.properties and tell it where to look:

```groovy
...

task importData(type: com.rjrudin.marklogic.gradle.task.MlcpTask) {
  ...
  output_uri_replace = ".*data,''"
  document_type = "binary"
  jvmArgs = ["-Dlog4j.configuration=file:" + file('conf/log4j.properties')]
}
```

Now it starts barking about a missing HADOOP_HOME env var.

So I added local mode:

```groovy
...

task importData(type: com.rjrudin.marklogic.gradle.task.MlcpTask) {
  ...
  output_uri_replace = ".*data,''"
  document_type = "binary"
  jvmArgs = ["-Dlog4j.configuration=file:" + file('conf/log4j.properties')]
  args = ["-mode", "local"]
}
```

Still no luck.

Output is:

```syslog
09:10:26.363 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
09:10:26.363 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java'.
09:10:26.367 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
09:10:26.368 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
09:10:26.368 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home/bin/java''
09:10:26.625 [QUIET] [system.out] DEBUG - ContentPump                - Command: IMPORT
09:10:26.625 [QUIET] [system.out] DEBUG - ContentPump                - Arguments: -host 10.211.55.11 -port 8000 -username admin -database trans-pacific-partnership-content -input_file_path data -document_type binary -output_collections pdf -output_uri_prefix /pdf -output_uri_replace .*data,'' -output_permissions rest-reader,read,rest-writer,update -mode local -password admin
09:10:26.665 [QUIET] [system.out] DEBUG - Shell                      - Failed to detect a valid hadoop home directory
09:10:26.665 [QUIET] [system.out] java.io.IOException: HADOOP_HOME or hadoop.home.dir are not set.
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:302)
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:327)
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438)
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484)
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
09:10:26.666 [QUIET] [system.out] 	at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
09:10:26.667 [QUIET] [system.out] 	at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:94)
09:10:26.667 [QUIET] [system.out] 	at com.marklogic.contentpump.ContentPump.main(ContentPump.java:67)
```

It's kind of lame that I have to specify the log4j.properties. But the HADOOP_HOME is the big issue. My guess it that I am missing some jar dependencies.

Ideas welcome.

**Comment by sastafford** [comment]
I ran into a similar issue where mlcp 1.3-3.  I did not run into the HADOOP_HOME error but I think there is a problem with the maven pom for mlcp on the marklogic maven site.  So the fix needs to come from engineering.  I submitted the following bug: https://bugtrack.marklogic.com/36053
Looks like a fix in 8.0-5

I am just using 1.3-2 for now.

**Comment by rjrudin** [comment]
From Andrew J - mlcp directly depends on Google guava library of version 11.0.2.  However, mlcp 1.3-3 and later also depends on a library (hadoop-auth) that has a transitive dependency that includes a newer version of this guava library.  Since gradle only allows one version of a library per dependency, mlcp was forced to use the newer version of the guava library, which had an API change that broke it.  Thus this bug report.  

It's easier to see this visually: http://www.screencast.com/t/fTpWn0DMH6C

For now, you can force gradle to use the 11.0.2 version for the entire mlcp package (including the hadoop-auth library) but I'm not sure what repercussions this may have on whatever apis mlcp uses from that hadoop-auth lib, since it's now using an older version of guava.  But my mlcp import tasks worked.

In my build.gradle, I added this to the configuration parameter for the mlcp config:

configurations {
  mlcp {
       resolutionStrategy.force 'com.google.guava:guava:11.0.2'
     }
}

**Comment by rjrudin** [comment]
Closing this, as it's due to a pom issue in the mlcp dependency
