### ISSUE TITLE
Accept property names with a 'marklogic.' prefix

### ISSUE THREAD

**Issue by sastafford** [rjrudin/ml-gradle#58]
As a developer
I want to Accept property names with a 'marklogic.' prefix
So that I can use a single properties file with ml-gradle and Spring Boot

At the World Bank, I've got two separate properties files, one for gradle, and one for Spring Boot with overlapping properties.  [Sprint Boot uses a properties naming convention](http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html) and I want to try to consolidate and get down to a single properties file.

**Comment by rjrudin** [comment]
This makes good sense - should it be done for the basic ML properties - e.g. mlHost, mlRestPort, mlTestRestPort, mlUsername, mlPassword, etc?

**Comment by sastafford** [comment]
Yes we should have that naming convention for all properties.  I just coded up one but I can do the rest.

**Comment by rjrudin** [comment]
Hey Scott - basic on some changes, the code for this is now in ml-app-deployer - see DefaultAppConfigFactory.

**Comment by rjrudin** [comment]
This has now been addressed in ml-app-deployer
