### ISSUE TITLE
getting sample project to work ... 

### ISSUE THREAD

**Issue by DALDEI** [rjrudin/ml-gradle#7]
I downloaded ml_gradle and ran gradle mlDeploy and it worked perfectly (the databases were created etc)  so to go further, following the docs I cloned sample-project did the same thing and its failing ...

Any ideas ? 
THis is running against a 8.0.1 release build of ML.

------> Not working
DLEE@DLEE-HP /cygdrive/c/Work/MarkLogic/Projects/mlui/gradle/test1/sample-project
$ gradle mlInstalLPackages
App name: sample-project
App host: vmnex
App username: admin
App REST port: 8100
App XDBC port: 8101
Manage app host: vmnex
Manage app username: admin
Couldn't find local.gradle; you can create this gitignore'd file to override properties if necessary
:mlPrepareRestApiDependencies
No mlRestApi dependencies found, so no preparation of dependencies required

:mlInstallPackages
Installing database and appserver packages
GET request for "http://vmnex:8002/manage/v2/packages/sample-project-package" resulted in 404 (Not Found); invoking error handler
POST request for "http://vmnex:8002/v1/rest-apis" resulted in 400 (Bad Request); invoking error handler
:mlInstallPackages FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlInstallPackages'.
> 400 Bad Request

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 12.299 secs

DLEE@DLEE-HP /cygdrive/c/Work/MarkLogic/Projects/mlui/gradle/test1/sample-project

---> Working

DLEE@DLEE-HP /cygdrive/c/Work/MarkLogic/Projects/mlui/gradle/test1
$ gradle mlInstalLPackages
App name: quick-start
App host: vmnex
App username: admin
App REST port: 8200
App XDBC port: 8201
Manage app host: vmnex
Manage app username: admin
:mlPrepareRestApiDependencies
No mlRestApi dependencies found, so no preparation of dependencies required

:mlMergeDatabasePackages
No mergePackageFilePaths specified, will not produce a new database package file
:mlMergeHttpServerPackages
No mergePackageFilePaths specified, will not produce a new HTTP server package file
:mlInstallPackages

Deleting package with quick-start-package
Sending a 'DELETE' to 'http://vmnex:8002/manage/v2/packages/quick-start-package'
Sending a 'GET' to 'http://vmnex:8002/manage/v2/packages/quick-start-package?format=json'

Creating package quick-start-package
Sending a 'POST' to 'http://vmnex:8002/manage/v2/packages?format=json&pkgname=quick-start-package'
No content database package file found, so not installing a content database

Checking to see if REST API with name quick-start exists...
Sending a 'GET' to 'http://vmnex:8002/v1/rest-apis/quick-start'
Creating new REST API server: {rest-api: {name: "quick-start", database: "quick-start-content", port: 8200}}
Sending a 'POST' to 'http://vmnex:8002/v1/rest-apis'

Adding server quick-start-content-xdbc in group Default to package quick-start-package
Sending a 'POST' to 'http://vmnex:8002/manage/v2/packages/quick-start-package/servers/quick-start-content-xdbc?group-id=Default'

Installing package quick-start-package
Sending a 'POST' to 'http://vmnex:8002/manage/v2/packages/quick-start-package/install?format=json'
Finished installing application quick-start

BUILD SUCCESSFUL

Total time: 19.348 secs

DLEE@DLEE-HP /cygdrive/c/Work/MarkLogic/Projects/mlui/gradle/test1
$

**Comment by rjrudin** [comment]
David - I think I fixed this by bumping up the version number of ml-gradle in the sample project to 1.1.2.
