### ISSUE TITLE
Read ML properties from Spring application.properties file

### ISSUE THREAD

**Issue by rjrudin** [rjrudin/ml-gradle#73]
To avoid duplication, it may be possible for ml-gradle to check for src/main/resources/application.properties and read ML properties from there, so they don't have to be defined there and in gradle.properties.

This can currently be achieved via the following block in a buildscript block:

    Properties props = new Properties()
    props.load(new FileInputStream("src/main/resources/application.properties"))
    props.each { prop ->
      if (prop.key.startsWith("marklogic")) {
        project.ext.set(prop.key, prop.value)
      }
    }

**Comment by sastafford** [comment]
It is expected that the properties live in gradle.props OR application.props?  Would they ever live in both?

**Comment by rjrudin** [comment]
I think the props have to live in application.props, because Spring is guaranteed to have that file in the jar that contains the webapp, whereas it's very doubtful that gradle.props would be include in the jar. 

Note that ml-app-deployer already has support for checking for e.g. "marklogic.mlHost" in case it can't find "mlHost".

**Comment by rjrudin** [comment]
I'm closing this, as I think slush-marklogic-spring-boot handles this in a very reasonable way already, and it strikes me as too Spring Boot-specific to try to cram into ml-gradle itself.
