### ISSUE TITLE
Can't add a new mimetype

### ISSUE THREAD

**Issue by sanderson-sfdc** [rjrudin/ml-gradle#79]
Using version 2.1.0.

Using the attached mimetype json, I am unable to add a new mimetype using gradle, but I am able to add the mimetype, using the same JSON file, via a direct POST.

`gradle -Penv=local mlDeploy
Applying environment-based build file: env-local.gradle
:mlDeleteModuleTimestampsFile
:mlPrepareRestApiDependencies
:mlDeployApp
PUT request for "http://localhost:8002/manage/v2/mimetypes/application/ditamap+xml/properties" resulted in 500 (Internal Server Error); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"500", "status":"Internal Server Error", "messageCode":"MANAGE-NOSUCHMIMETYPE", "message":"MANAGE-NOSUCHMIMETYPE (err:FOER0000): application/ditamap xml"}}
:mlDeployApp FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> 500 Internal Server Error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

`curl -X POST --anyauth -u admin:admin --header "Content-type:application/json" -d@ditamap.json http://localhost:8002/manage/v2/mimetypes
<restart xmlns="http://marklogic.com/manage">
  <last-startup host-id="3390806068089118510">2016-04-07T14:50:56.892339-07:00</last-startup>
  <link>
    <kindref>timestamp</kindref>
    <uriref>/admin/v1/timestamp</uriref>
  </link>
  <message>Check for new timestamp to verify host restart.</message>
</restart>
`
and

`curl -X GET --anyauth -u admin:admin --header "Content-type:application/json" http://localhost:8002/manage/v2/mimetypes |grep ditamap
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   209  100   209    0     0  33493      0 --:--:-- --:--:-- --:--:-- 34833
100 25224  100 25224    0     0  22838      0  0:00:01  0:00:01 --:--:-- 28151
      <uriref>/manage/v2/mimetypes/application/ditamap+xml</uriref>
      <nameref>application/ditamap+xml</nameref>`

I did notice in the gradle error it says it's using a PUT, but when I try to use a PUT, I got a REST-UNSUPPORTEDMETHOD error, not the one from the gradle command.

[ditamap.json.zip](https://github.com/rjrudin/ml-gradle/files/209287/ditamap.json.zip)

**Comment by rjrudin** [comment]
@sanderson-sfdc I reproduced this. The initial creation - via POST - works fine, but when ml-gradle tries to update the mapping via a PUT, the "+" is removed from the URL (it's trying to hit http://docs.marklogic.com/REST/PUT/manage/v2/mimetypes/[id-or-name]/properties ), and MarkLogic can't find the mimetype to update. 

I opened https://github.com/rjrudin/ml-app-deployer/issues/94 to capture the fix, and I'll leave this open until I've completed that.

**Comment by rjrudin** [comment]
I also noticed that ml-gradle isn't waiting for ML to restart - I don't know if that's new to ML 8.0-5 or has always been there, but I'll fix that as well.

**Comment by rjrudin** [comment]
Interesting - the Management API has this bug as well. If you go to localhost:8002/manage/v2/mimetypes and click on any mimetype with a "+" in it, you'll get a 404. Swapping out the plus for %2B does fix it, which seems to be the appropriate fix here. I'll file an ML bug as well.

**Comment by rjrudin** [comment]
I made the fix in ml-app-deployer for this - https://github.com/rjrudin/ml-app-deployer/issues/94 - this is in 2.2.0-RC1 of ml-gradle if you want to try it out.
