### ISSUE TITLE
gradle mlRestartCluster throws a 415 Unsupported Media Type

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#80]
Hi, 

when I execute the command gradle mlRestartCluster I get a 415 Unsupported Media Type error.

I'm running on ML8.0-5

gradle -Penv=dev mlRestartCluster
Applying environment-based build file: env-dev.gradle
:mlRestartCluster
POST request for "http://tradestore-vm-ml1:8002/manage/v2" resulted in 415 (Unsupported Media Type); invoking error handler
Logging HTTP response body to assist with debugging: {"errorResponse":{"statusCode":"415", "status":"Unsupported Media Type", "messageCode":"REST-INVALIDMIMETYPE", "message":"REST-INVALIDMIMETYPE: (rest:INVALIDMIMETYPE) Content-Type must be one of:  'application/x-www-form-urlencoded', Received: application/json"}}
:mlRestartCluster FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlRestartCluster'.
> 415 Unsupported Media Type

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.471 secs

**Comment by rjrudin** [comment]
Thanks @peetkes - sounds like state=restart will work on 8.04 and 8.05. I'll get a fix into 2.1.1 for this.

**Comment by rjrudin** [comment]
Turned out to be a simple change:

client.postForm("/manage/v2", "state", "restart")
