### ISSUE TITLE
Option to order the creation of roles in the security db

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#86]
When I have multiple roles with dependencies, the deployRoles will fail if the first one to deploy has a reference to a not-yet deployed role. Can we force ordering of roles on deploy?

**Comment by sastafford** [comment]
Prefix the file with a number representing the order to apply

 
 
  On Fri, Apr 15, 2016 at 6:55 AM, Peter Kester<notifications@github.com> wrote:   
When I have multiple roles with dependencies, the deployRoles will fail if the first one to deploy has a reference to a not-yet deployed role. Can we force ordering of roles on deploy?

**Comment by rjrudin** [comment]
What @sastafford  said - ordering of files for any resource can be set via numbers at the start of the files (I've only had to do this for roles, FWIW).

**Comment by grtjn** [comment]
Ordering wouldn't be necessary, if all roles would be created first, and linked only after that.

The rest api shpuld take care of this i'd say..


Sent from Samsung Mobile

-------- Oorspronkelijk bericht --------
Van: Peter Kester <notifications@github.com> 
Datum: 15-04-2016  12:55  (GMT+01:00) 
Aan: rjrudin/ml-gradle <ml-gradle@noreply.github.com> 
Onderwerp: [rjrudin/ml-gradle] Option to order the creation of roles in the security db (#86) 
 
When I have multiple roles with dependencies, the deployRoles will fail if the first one to deploy has a reference to a not-yet deployed role. Can we force ordering of roles on deploy?

**Comment by rjrudin** [comment]
@grtjn I think that's something that'll appear in future versions of the Mgmt REST API - perhaps an endpoint that takes a payload with multiple roles in it, and then the endpoint takes care of the hard work of creating them in the right order and linking them up.
