### ISSUE TITLE
Show example of creating a role that refers to itself

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#87]
I get a SEC_ROLEDNE error when I create a role with a permission.
{
  "role-name" : "tradestore-read-role",
  "role" : [ "rest-reader" ],
  "permission": [
    {
      "role-name": "tradestore-read-role",
      "capability": "read"
    }
  ]
}
It kinda makes sense, because in the admin interface you cannot do this as well, but then we need some kind of mechanism to get those permissions added to the role.
Maybe split this up in a two step task, first step is create the role, second step is to add the permissions.

**Comment by xquery** [comment]
yes you have to first create with POST then PUT the perms on the role .... we may add an 'all in one' approach but in general we avoid this kind of thing with the manage rest api (eg have smart scripts, clean endpoints).

**Comment by peetkes** [comment]
Will ml-gradle support this?

**Comment by sastafford** [comment]
To follow on Jim's earlier comment.  ml-gradle is lock-step in line with the Management REST API.  ml-gradle will support this call and it's along the same answer as issue #86.  

File Name: 1-tradestore-read-role.json
{
	"role-name": "tradestore-read-role",
	"role": ["rest-reader"]
}


File Name: 2-tradestore-read-role-2.json
{
	"role-name": "tradestore-read-role",
	"permission": [{
		"role-name": "tradestore-read-role",
		"capability": "read"
	}]
}

**Comment by rjrudin** [comment]
I like Scott's suggestion, I hadn't thought of that. You could make a custom command or task too that does a PUT and just includes the permissions, but I think Scott's approach is better. 

Note that the trick of putting numbers at the front of the file is common to use for roles, as there are often dependencies between role files.

**Comment by rjrudin** [comment]
@peetkes How does Roxy support it? Is it by having something akin to what Scott suggested - two blocks in the config file for the role, the 2nd one having the permissions?

**Comment by peetkes** [comment]
@rjrudin That is exactly how roxy supports it. It does a multi step deploy, first it creates the role and then adds the permissions, collections and such.. The workaround that @sastafford  suggested works also very well.

**Comment by rjrudin** [comment]
Good suggestion, I'm going to re-title this based on providing an example
