### ISSUE TITLE
Add support for generate_uri option for mlcp task

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#89]
The option generate_uri is not supported by the mlcp task.

**Comment by sastafford** [comment]
You can pass in a generic set of arguments
args = ["-outputuri", "uri"]

 
 
  On Sat, Apr 16, 2016 at 10:49 AM, Peter Kester<notifications@github.com> wrote:   
The option generate_uri is not supported by the mlcp task.

**Comment by peetkes** [comment]
Ok, thanks didn't know that

**Comment by rjrudin** [comment]
Yeah, I've been meaning to expand the set of arguments, but it's all syntactic sugar, since MlcpTask extends Gradle's JavaExec task, which has that args array.
