### ISSUE TITLE
Import of csv file fails on the delimiter

### ISSUE THREAD

**Issue by peetkes** [rjrudin/ml-gradle#90]
I'm trying to import a csv file that uses the ; as delimiter but the mlcp call seems to not understand this. How do I need to escape the ; as delimiter?
I use the following task for this:
    task importCSVData(type: com.marklogic.gradle.task.MlcpTask) {
        classpath = configurations.mlcp
        command = "IMPORT"
        database = mlAppConfig.contentDatabaseName
        input_file_type = "delimited_text"
        input_file_path = "../../test-data/reference-data/clean"
        input_file_pattern = ".*\\.csv"
        namespace = "http://someuri/ts/cpty"
        delimited_root_name = "ReferenceData"
        output_collections = "data,data/Reference"
        output_uri_replace = "^[/\\\\\\\\]?(?:.+[/\\\\\\\\]+?)?(.+?)[/\\\\\\\\]?\$,'/TradeStore/\$1'"
        thread_count = "8"
        transform_module="/transform/mlcp-transform.xqy"
        transform_namespace = "http://someuri/ts/mlcp-transform"
        output_permissions = "app-read-role,read,app-update-role,update,app-insert-role,insert"
        args=["-generate_uri","true","-transform_function","transform","-delimiter",";"]
    }

I don't get any error messages but also no files are imported

**Comment by grtjn** [comment]
You could by-pass the issue with an options file perhaps..

**Comment by peetkes** [comment]
No, tried that as well with the same result.

**Comment by sastafford** [comment]
I'm pretty sure you have to use an options file.
http://docs.marklogic.com/guide/mlcp/import#id_24824

This is not a ml-gradle bug.  Recommend to close this issue.  
 

    On Sunday, April 17, 2016 8:05 AM, Peter Kester <notifications@github.com> wrote:
 

 No, tried that as well with the same result.

**Comment by rjrudin** [comment]
Hey @peetkes - I just tried to reproduce with the below config and sample file, and it worked fine. Gradle/Groovy doesn't require escaping a semicolon in quotes. I'm on Windows, FWTW. 

task test(type: com.marklogic.gradle.task.MlcpTask) {
    classpath = configurations.mlcp
    command = "IMPORT"
    database = mlAppConfig.contentDatabaseName
    input_file_type = "delimited_text"
    input_file_path = "data/import/semicolon.txt"
    output_collections = "sample-import"
    output_permissions = "rest-reader,read,rest-writer,update"
    output_uri_replace = ".*import,'/import'"
    args = ["-delimiter", ";"]
}

Sample file:

first;second;third
quick;brown;fox
hello;world;again

**Comment by peetkes** [comment]
@rjrudin I think the issue lies with the mlcp version used.
if the mlcp dependency points to "com.marklogic:mlcp-Hadoop2:1.3-2" it will work and if the mlcp dependency points to "com.marklogic:mlcp:8.0-5" which is the latest version, it will return no errors but no files get imported into MarkLogic.

**Comment by rjrudin** [comment]
@peetkes Did you get this working with a plain mlcp install?

**Comment by peetkes** [comment]
Yes, a plain installation and running from commandline does work

**Comment by rjrudin** [comment]
@peetkes See the above commit - mlcp-project now has an example of doing an import with a semi-colon as the delimiter. I did have to add commons-csv to the mlcp configuration - apparently, the mlcp dependency does not include that by default (which seems reasonable).
