### ISSUE TITLE
Does ml-support deployment of just an app server?

### ISSUE THREAD

**Issue by tzejohn** [rjrudin/ml-gradle#98]
I would like to configure an app server that uses existing databases, and will not itself create/recreate existing databases.  Is this possible?

**Comment by rjrudin** [comment]
Yes - the mlAppDeployer Gradle variable, which is an instance of SimpleAppDeployer from ml-app-deployer, has a list of default commands populated by ml-gradle. You can manipulate that list however you want - the sample-project/build.gradle file shows some examples of doing so. Two options for this use case:

1. You can call clear() on mlAppDeployer.commands, and then add an instance of DeployOtherServersCommand
1. You can remove the instance of DeployRestApiServersCommand (I should really provide a property to disable this).

#2 is probably the easier option, as DeployRestApiServersCommand is the only command that does something by default, even if no payload file exists. Here's how:

    ext {
      def c = mlAppDeployer.getCommand("DeployRestApiServersCommand")
      mlAppDeployer.commands.remove(c)
    }

**Comment by tzejohn** [comment]
Understood, thanks.  So, if I wanted to setup just another REST endpoint to an existing content/modules db, I could create a separate project, where I can clear all of the commands, and only include the DeployRestApiServersCommand and UpdateRestApiServersCommand, plus any others I need, and then there would be no case where I would unintentionally create another content database with the new app name.  Specifically I am looking to setup another REST endpoint with different authentication mechanism (application-level).

**Comment by rjrudin** [comment]
If your use case is stand up a REST API server with an existing content database, just modify src/main/ml-modules/rest-api.json so that it refers to the existing content and/or modules databases. Then you don't need to do anything with mlAppDeployer.
